In [1]:
import pandas as pd
import numpy as np

In [2]:
df1=pd.read_excel('DF_INCOMP.xlsx')
df2=pd.read_excel('df_COMPLETE.xlsx')

In [3]:
df1

,SN,AGE,CYCLE,BLOOD GROUP,GENOTYPE,FSH 1 – 10 (miu/ml),LH 1 – 10.5 (miu/ml),PRL 1 – 16 (ng/ml)
0,1,29,MENSES,O POS,AA,8.77,7.52,36.78
1,2,36,MENSES,O POS,AA,4.53,2.41,10.67
2,3,33,MENSES,O POS,AA,4.45,8.10,16.75
3,4,36,MENSES,O POS,AA,4.57,6.70,12.51
4,5,25,MENSES,O POS,AA,4.56,5.47,8.23
...,...,...,...,...,...,...,...,...
185,186,38,MENSES,O POS,AA,12.15,8.99,31.62
186,187,33,MENSES,A POS,AA,10.00,6.88,21.49
187,188,25,MENSES,O POS,AA,6.20,7.86,14.36
188,189,33,MENSES,O POS,AS,6.83,8.53,11.48
189,190,25,MENSES,B POS,AA,4.86,4.64,6.76

In [4]:
display('df1', 'df2', 'pd.concat([df1, df2])')

'df1'

'df2'

'pd.concat([df1, df2])'

In [5]:
combined_df= pd.concat([df1, df2])

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.

In [6]:
combined_df

,AGE,BLOOD GROUP,CYCLE,Cd (mg/L),Cr (mg/L),FSH 1 – 10 (miu/ml),GENOTYPE,Hg (mg/L),LH 1 – 10.5 (miu/ml),PRL 1 – 16 (ng/ml),Pb (mg/L),SN
0,29,O POS,MENSES,NaN,NaN,8.77,AA,NaN,7.52,36.78,NaN,1
1,36,O POS,MENSES,NaN,NaN,4.53,AA,NaN,2.41,10.67,NaN,2
2,33,O POS,MENSES,NaN,NaN,4.45,AA,NaN,8.10,16.75,NaN,3
3,36,O POS,MENSES,NaN,NaN,4.57,AA,NaN,6.70,12.51,NaN,4
4,25,O POS,MENSES,NaN,NaN,4.56,AA,NaN,5.47,8.23,NaN,5
...,...,...,...,...,...,...,...,...,...,...,...,...
25,48,NaN,NaN,-0.0130,-2.7481,NaN,NaN,0.0007,NaN,NaN,0.0209,73
26,51,NaN,NaN,-0.0121,-2.5226,NaN,NaN,0.6732,NaN,NaN,0.0259,74
27,25,NaN,NaN,-0.0080,-2.0882,NaN,NaN,0.7699,NaN,NaN,-0.0052,78
28,37,NaN,NaN,-0.0071,-2.3184,NaN,NaN,-1.1219,NaN,NaN,1.7677,79
29,41,NaN,NaN,-0.0083,-2.4411,NaN,NaN,-0.8372,NaN,NaN,0.0972,83

In [7]:
pd.set_option('display.max_rows', combined_df.shape[0]+1)

In [8]:
combined_df

,AGE,BLOOD GROUP,CYCLE,Cd (mg/L),Cr (mg/L),FSH 1 – 10 (miu/ml),GENOTYPE,Hg (mg/L),LH 1 – 10.5 (miu/ml),PRL 1 – 16 (ng/ml),Pb (mg/L),SN
0,29,O POS,MENSES,NaN,NaN,8.77,AA,NaN,7.52,36.78,NaN,1
1,36,O POS,MENSES,NaN,NaN,4.53,AA,NaN,2.41,10.67,NaN,2
2,33,O POS,MENSES,NaN,NaN,4.45,AA,NaN,8.10,16.75,NaN,3
3,36,O POS,MENSES,NaN,NaN,4.57,AA,NaN,6.70,12.51,NaN,4
4,25,O POS,MENSES,NaN,NaN,4.56,AA,NaN,5.47,8.23,NaN,5
5,44,A POS,MENSES,NaN,NaN,3.72,AS,NaN,5.13,27.45,NaN,6
6,35,A POS,MENSES,NaN,NaN,4.16,AA,NaN,6.38,42.52,NaN,7
7,33,O POS,MENSES,NaN,NaN,6.13,AA,NaN,7.19,13.33,NaN,8
8,36,O POS,MENSES,NaN,NaN,10.23,AA,NaN,7.27,16.08,NaN,9
9,39,O POS,MENSES,NaN,NaN,2.39,AA,NaN,3.79,4.76,NaN,10
10,44,A POS,MENSES,NaN,NaN,5.10,AS,NaN,4.21,22.21,NaN,11
11,29,O POS,MENSES,NaN,NaN,7.99,AA,NaN,4.57,14.69,NaN,12
12,30,O POS,MENSES,NaN,NaN,3.79,AA,NaN,3.44,6.73,NaN,13
13,36,O POS,MENSES,NaN,NaN,4.36,AA,NaN,1.29,54.20,NaN,14
14,30,O POS,MENSES,NaN,NaN,7.25,AA,NaN,6.73,6.80,NaN,15
15,27,O POS,MENSES,NaN,NaN,5.37,AA,NaN,7.54,11.91,NaN,16
16,25,B POS,MENSES,NaN,NaN,3.63,AA,NaN,4.47,20.36,NaN,17
17,33,A POS,MENSES,NaN,NaN,4.56,AS,NaN,8.27,30.41,NaN,18
18,34,O POS,MENSES,NaN,NaN,2.34,AA,NaN,3.42,6.91,NaN,19
19,32,O POS,MENSES,NaN,NaN,8.05,AA,NaN,4.56,3.78,NaN,20
20,36,O POS,MENSES,NaN,NaN,5.96,AA,NaN,7.22,10.51,NaN,21
21,25,O POS,MENSES,NaN,NaN,7.13,AA,NaN,10.92,10.79,NaN,22
22,35,B POS,MENSES,NaN,NaN,6.43,AS,NaN,9.83,16.64,NaN,23
23,33,A POS,MENSES,NaN,NaN,6.94,AA,NaN,4.92,25.21,NaN,24
24,30,O POS,MENSES,NaN,NaN,8.64,AA,NaN,8.55,17.87,NaN,25
25,28,O POS,MENSES,NaN,NaN,4.79,AA,NaN,6.18,28.21,NaN,26
26,25,O POS,MENSES,NaN,NaN,4.11,AA,NaN,6.61,4.16,NaN,27
27,49,O POS,NON MENSES,NaN,NaN,5.17,AS,NaN,6.96,6.49,NaN,28
28,32,A POS,MENSES,NaN,NaN,14.30,AA,NaN,12.70,1.13,NaN,29
29,26,A POS,MENSES,NaN,NaN,6.75,AA,NaN,4.47,4.91,NaN,30
30,24,B POS,MENSES,NaN,NaN,3.65,AA,NaN,4.62,30.03,NaN,31
31,27,O POS,MENSES,NaN,NaN,6.76,AA,NaN,5.89,6.23,NaN,32
32,36,O POS,MENSES,NaN,NaN,6.47,AA,NaN,7.54,20.18,NaN,33
33,33,O POS,MENSES,NaN,NaN,5.05,AA,NaN,8.25,4.86,NaN,34
34,32,B POS,MENSES,NaN,NaN,10.35,AA,NaN,8.89,13.74,NaN,35
35,24,B POS,MENSES,NaN,NaN,9.63,AA,NaN,23.50,15.43,NaN,36
36,36,O POS,MENSES,NaN,NaN,8.77,AA,NaN,7.50,7.22,NaN,37
37,40,O POS,MENSES,NaN,NaN,10.21,AA,NaN,1.23,35.80,NaN,38
38,28,B POS,MENSES,NaN,NaN,3.71,AS,NaN,6.67,9.59,NaN,39
39,43,O POS,MENSES,NaN,NaN,17.12,AA,NaN,8.39,10.75,NaN,40
40,42,O POS,NON MENSES,NaN,NaN,6.32,AA,NaN,5.01,40.42,NaN,41
41,30,O POS,MENSES,NaN,NaN,8.81,AA,NaN,4.91,20.06,NaN,42
42,28,A POS,MENSES,NaN,NaN,5.20,AA,NaN,2.83,10.20,NaN,43
43,30,O POS,MENSES,NaN,NaN,5.02,AA,NaN,9.40,12.46,NaN,44
44,34,O POS,MENSES,NaN,NaN,4.87,AA,NaN,3.69,12.84,NaN,45
45,37,B POS,MENSES,NaN,NaN,11.82,AA,NaN,11.12,8.33,NaN,46
46,48,B POS,MENSES,NaN,NaN,5.57,AA,NaN,4.51,54.39,NaN,47
47,30,O POS,MENSES,NaN,NaN,5.11,AA,NaN,8.38,12.35,NaN,48
48,29,O POS,MENSES,NaN,NaN,7.55,AA,NaN,4.27,13.62,NaN,49
49,27,A POS,MENSES,NaN,NaN,6.56,AA,NaN,4.56,4.82,NaN,50
50,28,O POS,MENSES,NaN,NaN,5.57,AA,NaN,5.57,35.80,NaN,51
51,35,O POS,MENSES,NaN,NaN,4.62,AA,NaN,3.12,9.67,NaN,52
52,34,B POS,MENSES,NaN,NaN,4.35,AA,NaN,7.10,15.75,NaN,53
53,25,A POS,MENSES,NaN,NaN,4.46,AA,NaN,4.47,7.23,NaN,54
54,44,B POS,MENSES,NaN,NaN,3.62,AS,NaN,5.20,28.12,NaN,55
55,33,O POS,MENSES,NaN,NaN,5.13,AA,NaN,6.19,13.30,NaN,56
56,44,A POS,MENSES,NaN,NaN,5.08,AS,NaN,4.36,27.40,NaN,57
57,30,O POS,MENSES,NaN,NaN,3.59,AA,NaN,4.22,6.67,NaN,58
58,30,O POS,MENSES,NaN,NaN,7.21,AA,NaN,6.40,6.50,NaN,59
59,26,O POS,MENSES,NaN,NaN,5.55,AA,NaN,6.54,10.86,NaN,60
60,34,O POS,MENSES,NaN,NaN,4.25,AS,NaN,7.27,28.17,NaN,61
61,36,O POS,MENSES,NaN,NaN,3.34,AA,NaN,4.44,6.63,NaN,62
62,37,O POS,MENSES,NaN,NaN,5.42,AS,NaN,7.84,14.53,NaN,63
63,34,O POS,MENSES,NaN,NaN,5.84,AA,NaN,4.72,25.31,NaN,64
64,27,B POS,MENSES,NaN,NaN,4.76,AA,NaN,6.24,30.01,NaN,65
65,35,O POS,MENSES,NaN,NaN,5.42,AA,NaN,6.24,19.17,NaN,66
66,33,B POS,MENSES,NaN,NaN,9.12,AA,NaN,8.54,10.70,NaN,67
67,37,O POS,MENSES,NaN,NaN,6.25,AA,NaN,5.22,5.24,NaN,68
68,31,O POS,MENSES,NaN,NaN,5.84,AA,NaN,3.61,18.69,NaN,69
69,35,O POS,MENSES,NaN,NaN,4.27,AA,NaN,3.14,10.54,NaN,70
70,37,B POS,MENSES,NaN,NaN,10.81,AA,NaN,9.57,7.23,NaN,71
71,47,B POS,MENSES,NaN,NaN,5.65,AA,NaN,4.62,50.32,NaN,72
72,48,O POS,NON MENSES,NaN,NaN,77.22,AA,NaN,61.15,10.50,NaN,73
73,51,O POS,NON MENSES,NaN,NaN,96.55,AA,NaN,70.42,13.47,NaN,74
74,34,O POS,MENSES,NaN,NaN,6.07,AA,NaN,5.18,5.29,NaN,75
75,36,O POS,MENSES,NaN,NaN,4.97,AA,NaN,4.81,20.26,NaN,76
76,35,A POS,MENSES,NaN,NaN,5.77,AA,NaN,4.82,7.41,NaN,77
77,25,O POS,MENSES,NaN,NaN,3.61,AA,NaN,4.40,5.03,NaN,78
78,37,O POS,MENSES,NaN,NaN,5.61,AA,NaN,5.28,17.16,NaN,79
79,33,A POS,MENSES,NaN,NaN,5.66,AA,NaN,5.84,8.21,NaN,80
80,35,O POS,MENSES,NaN,NaN,6.11,AA,NaN,6.43,5.57,NaN,81
81,28,A POS,MENSES,NaN,NaN,3.74,AA,NaN,3.36,2.56,NaN,82
82,41,O NEG,MENSES,NaN,NaN,9.22,AA,NaN,6.25,12.38,NaN,83
83,35,O POS,MENSES,NaN,NaN,10.10,AA,NaN,7.93,8.83,NaN,84
84,35,O POS,MENSES,NaN,NaN,6.35,AA,NaN,5.93,17.43,NaN,85
85,43,O POS,MENSES,NaN,NaN,3.93,AA,NaN,4.82,10.97,NaN,86
86,41,AB POS,MENSES,NaN,NaN,10.32,AA,NaN,7.39,6.82,NaN,87
87,40,O POS,MENSES,NaN,NaN,9.81,AA,NaN,9.33,12.60,NaN,88
88,31,O POS,MENSES,NaN,NaN,10.84,AA,NaN,17.35,20.87,NaN,89
89,29,A POS,MENSES,NaN,NaN,5.10,AA,NaN,3.41,3.00,NaN,90
90,42,O NEG,MENSES,NaN,NaN,7.56,AA,NaN,5.52,10.50,NaN,91
91,44,O POS,MENSES,NaN,NaN,4.39,AA,NaN,4.71,10.22,NaN,92
92,28,A POS,MENSES,NaN,NaN,3.44,AA,NaN,4.62,5.00,NaN,93
93,42,O POS,MENSES,NaN,NaN,3.96,AA,NaN,3.87,9.43,NaN,94
94,48,O POS,NON MENSES,NaN,NaN,16.93,AA,NaN,13.82,65.33,NaN,95
95,51,O POS,NON MENSES,NaN,NaN,20.44,AA,NaN,31.14,18.72,NaN,96
96,35,O POS,MENSES,NaN,NaN,27.22,AA,NaN,5.14,38.85,NaN,97
97,30,O POS,MENSES,NaN,NaN,6.74,AA,NaN,9.41,5.34,NaN,98
98,41,O POS,MENSES,NaN,NaN,6.63,AA,NaN,7.83,6.39,NaN,99
99,31,O POS,MENSES,NaN,NaN,5.93,AA,NaN,4.28,13.50,NaN,100
100,27,B POS,MENSES,NaN,NaN,8.38,AA,NaN,5.62,5.42,NaN,101
101,25,B POS,MENSES,NaN,NaN,5.74,AA,NaN,8.25,8.03,NaN,102
102,23,O POS,MENSES,NaN,NaN,8.56,AA,NaN,11.48,77.07,NaN,103
103,44,O POS,MENSES,NaN,NaN,7.72,AA,NaN,5.18,25.21,NaN,104
104,29,O NEG,MENSES,NaN,NaN,5.13,AA,NaN,1.52,7.45,NaN,105
105,31,O POS,MENSES,NaN,NaN,8.66,AA,NaN,5.88,6.94,NaN,106
106,36,O POS,MENSES,NaN,NaN,8.78,AA,NaN,4.60,6.17,NaN,107
107,30,B POS,MENSES,NaN,NaN,7.83,AA,NaN,6.02,5.38,NaN,108
108,24,B POS,MENSES,NaN,NaN,5.21,AA,NaN,7.17,7.08,NaN,109
109,25,B POS,MENSES,NaN,NaN,6.91,AA,NaN,7.65,11.32,NaN,110
110,40,AB POS,MENSES,NaN,NaN,32.07,AS,NaN,15.29,43.17,NaN,111
111,24,O POS,MENSES,NaN,NaN,8.61,AA,NaN,10.78,9.79,NaN,112
112,38,O POS,MENSES,NaN,NaN,6.89,AA,NaN,15.27,12.60,NaN,113
113,41,O POS,MENSES,NaN,NaN,8.90,AA,NaN,11.42,3.82,NaN,114
114,32,O POS,MENSES,NaN,NaN,10.72,AA,NaN,7.40,22.37,NaN,115
115,32,B POS,MENSES,NaN,NaN,9.95,AA,NaN,6.55,28.62,NaN,116
116,32,O POS,NON MENSES,NaN,NaN,20.26,AA,NaN,11.94,13.13,NaN,117
117,28,B POS,MENSES,NaN,NaN,7.40,AA,NaN,5.99,9.17,NaN,118
118,29,O POS,MENSES,NaN,NaN,9.06,AA,NaN,8.03,9.03,NaN,119
119,40,O POS,MENSES,NaN,NaN,7.30,AA,NaN,5.50,20.57,NaN,120
120,25,O POS,MENSES,NaN,NaN,5.28,AA,NaN,10.25,6.72,NaN,121
121,32,O POS,MENSES,NaN,NaN,6.94,AA,NaN,7.74,15.83,NaN,122
122,39,O POS,MENSES,NaN,NaN,7.85,AA,NaN,10.57,7.51,NaN,123
123,37,A POS,MENSES,NaN,NaN,10.22,AS,NaN,10.07,15.59,NaN,124
124,26,O POS,MENSES,NaN,NaN,6.22,AA,NaN,13.79,14.36,NaN,125
125,43,O POS,MENSES,NaN,NaN,14.49,AS,NaN,24.17,21.24,NaN,126
126,36,O POS,NON MENSES,NaN,NaN,24.08,AA,NaN,3.14,82.12,NaN,127
127,25,AB POS,MENSES,NaN,NaN,6.18,AA,NaN,3.90,6.85,NaN,128
128,29,O POS,MENSES,NaN,NaN,7.54,AA,NaN,5.45,11.07,NaN,129
129,35,AB POS,MENSES,NaN,NaN,9.77,AA,NaN,7.13,14.03,NaN,130
130,32,A POS,MENSES,NaN,NaN,6.88,AA,NaN,5.97,13.92,NaN,131
131,23,O POS,MENSES,NaN,NaN,9.19,AA,NaN,6.67,16.05,NaN,132
132,23,O POS,MENSES,NaN,NaN,7.82,AA,NaN,8.25,12.13,NaN,133
133,35,O POS,MENSES,NaN,NaN,6.36,AA,NaN,7.23,7.55,NaN,134
134,25,O POS,MENSES,NaN,NaN,6.36,AS,NaN,7.23,7.55,NaN,135
135,23,O POS,MENSES,NaN,NaN,5.72,AA,NaN,3.72,26.35,NaN,136
136,30,O POS,MENSES,NaN,NaN,4.93,AA,NaN,6.35,13.71,NaN,137
137,45,O POS,MENSES,NaN,NaN,2.71,AA,NaN,1.27,54.11,NaN,138
138,40,O POS,MENSES,NaN,NaN,6.97,AA,NaN,6.85,13.47,NaN,139
139,43,O POS,NON MENSES,NaN,NaN,38.83,AA,NaN,34.72,14.50,NaN,140
140,34,O POS,MENSES,NaN,NaN,6.02,AA,NaN,5.25,9.98,NaN,141
141,35,O POS,MENSES,NaN,NaN,7.48,AS,NaN,6.65,10.57,NaN,142
142,40,O POS,MENSES,NaN,NaN,10.27,AA,NaN,15.42,15.60,NaN,143
143,37,A POS,MENSES,NaN,NaN,8.89,AA,NaN,6.68,15.60,NaN,144
144,25,O POS,MENSES,NaN,NaN,5.58,AA,NaN,5.42,9.13,NaN,145
145,40,O POS,MENSES,NaN,NaN,14.67,AA,NaN,9.20,98.48,NaN,146
146,39,B POS,MENSES,NaN,NaN,10.28,AA,NaN,5.85,16.85,NaN,147
147,38,O NEG,MENSES,NaN,NaN,15.25,AA,NaN,13.55,17.20,NaN,148
148,23,O POS,MENSES,NaN,NaN,7.00,AA,NaN,1.65,6.13,NaN,149
149,39,O POS,MENSES,NaN,NaN,3.88,AA,NaN,6.16,14.01,NaN,150
150,41,O POS,MENSES,NaN,NaN,5.83,AA,NaN,5.04,6.92,NaN,151
151,46,O POS,MENSES,NaN,NaN,20.37,AS,NaN,22.96,38.44,NaN,152
152,43,B POS,MENSES,NaN,NaN,7.83,AA,NaN,5.87,26.11,NaN,153
153,39,AB NEG,MENSES,NaN,NaN,13.11,AS,NaN,13.53,36.22,NaN,154
154,43,A POS,MENSES,NaN,NaN,2.87,AS,NaN,4.23,13.73,NaN,155
155,39,O POS,MENSES,NaN,NaN,22.72,AA,NaN,17.22,5.28,NaN,156
156,43,B POS,MENSES,NaN,NaN,8.86,AA,NaN,11.98,24.11,NaN,157
157,30,O POS,MENSES,NaN,NaN,4.93,AS,NaN,4.63,22.14,NaN,158
158,32,O POS,MENSES,NaN,NaN,6.20,AA,NaN,4.68,13.37,NaN,159
159,35,O POS,MENSES,NaN,NaN,5.75,AA,NaN,9.39,16.40,NaN,160
160,38,O POS,MENSES,NaN,NaN,9.81,AA,NaN,10.11,10.58,NaN,161
161,36,A POS,MENSES,NaN,NaN,6.03,AA,NaN,3.35,18.55,NaN,162
162,38,O NEG,MENSES,NaN,NaN,5.60,AA,NaN,18.77,15.76,NaN,163
163,40,O POS,MENSES,NaN,NaN,5.80,AA,NaN,6.79,10.76,NaN,164
164,40,O POS,MENSES,NaN,NaN,7.48,AA,NaN,11.24,15.01,NaN,165
165,40,O POS,MENSES,NaN,NaN,5.35,AA,NaN,6.38,5.72,NaN,166
166,39,B POS,MENSES,NaN,NaN,10.28,AA,NaN,5.40,14.25,NaN,167
167,40,O POS,MENSES,NaN,NaN,9.82,AA,NaN,8.39,31.03,NaN,168
168,47,O POS,MENSES,NaN,NaN,8.75,AA,NaN,7.47,8.62,NaN,169
169,32,O POS,MENSES,NaN,NaN,8.80,AA,NaN,7.64,45.93,NaN,170
170,40,O POS,MENSES,NaN,NaN,5.91,AA,NaN,9.38,10.10,NaN,171
171,25,A POS,MENSES,NaN,NaN,6.01,AA,NaN,7.89,14.44,NaN,172
172,25,O POS,MENSES,NaN,NaN,5.77,AA,NaN,9.95,13.61,NaN,173
173,28,O POS,MENSES,NaN,NaN,8.11,AA,NaN,10.42,6.27,NaN,174
174,30,B POS,MENSES,NaN,NaN,6.35,AA,NaN,6.18,8.54,NaN,175
175,31,O POS,MENSES,NaN,NaN,10.07,AS,NaN,6.17,13.60,NaN,176
176,41,A POS,MENSES,NaN,NaN,6.90,AA,NaN,5.91,23.25,NaN,177
177,36,O POS,MENSES,NaN,NaN,13.61,AA,NaN,7.34,9.90,NaN,178
178,34,O POS,MENSES,NaN,NaN,5.81,AA,NaN,4.58,14.14,NaN,179
179,20,A POS,MENSES,NaN,NaN,4.41,AA,NaN,3.99,4.38,NaN,180
180,32,O POS,MENSES,NaN,NaN,5.59,AS,NaN,7.02,7.90,NaN,181
181,24,O POS,MENSES,NaN,NaN,3.90,AA,NaN,10.02,5.59,NaN,182
182,23,O POS,MENSES,NaN,NaN,5.02,AA,NaN,7.36,11.65,NaN,183
183,28,B POS,MENSES,NaN,NaN,5.25,AA,NaN,5.63,5.79,NaN,184
184,27,A POS,MENSES,NaN,NaN,8.07,AS,NaN,8.26,29.13,NaN,185
185,38,O POS,MENSES,NaN,NaN,12.15,AA,NaN,8.99,31.62,NaN,186
186,33,A POS,MENSES,NaN,NaN,10.00,AA,NaN,6.88,21.49,NaN,187
187,25,O POS,MENSES,NaN,NaN,6.20,AA,NaN,7.86,14.36,NaN,188
188,33,O POS,MENSES,NaN,NaN,6.83,AS,NaN,8.53,11.48,NaN,189
189,25,B POS,MENSES,NaN,NaN,4.86,AA,NaN,4.64,6.76,NaN,190
0,36,NaN,NaN,-0.0189,0.4989,NaN,NaN,6.6777,NaN,NaN,0.0755,2
1,44,NaN,NaN,-0.0065,0.2351,NaN,NaN,2.4756,NaN,NaN,0.0409,6
2,35,NaN,NaN,-0.0035,-0.4379,NaN,NaN,0.7624,NaN,NaN,0.0604,7
3,39,NaN,NaN,-0.0104,-1.0635,NaN,NaN,0.4657,NaN,NaN,0.1126,10
4,44,NaN,NaN,-0.0147,-0.7069,NaN,NaN,-0.7568,NaN,NaN,0.0501,11
5,36,NaN,NaN,-0.0408,-0.7493,NaN,NaN,-0.6593,NaN,NaN,-0.0318,14
6,33,NaN,NaN,-0.0188,-1.0267,NaN,NaN,-0.9343,NaN,NaN,0.0035,18
7,35,NaN,NaN,-0.0130,-1.1012,NaN,NaN,-2.7321,NaN,NaN,0.0273,23
8,49,NaN,NaN,-0.0240,-1.0158,NaN,NaN,-2.6558,NaN,NaN,0.0210,28
9,24,NaN,NaN,-0.0104,-1.9163,NaN,NaN,-2.3514,NaN,NaN,0.0516,31
10,24,NaN,NaN,-0.0087,-1.4783,NaN,NaN,-2.8384,NaN,NaN,0.0525,36
11,40,NaN,NaN,-0.0125,-1.5972,NaN,NaN,-1.1419,NaN,NaN,0.0469,38
12,43,NaN,NaN,-0.0094,-1.3596,NaN,NaN,-1.6096,NaN,NaN,0.0748,40
13,42,NaN,NaN,-0.0076,-1.2802,NaN,NaN,-1.7066,NaN,NaN,-0.0590,41
14,28,NaN,NaN,-0.0122,-1.9279,NaN,NaN,-0.7858,NaN,NaN,-0.0461,43
15,30,NaN,NaN,-0.0120,-0.3216,NaN,NaN,-0.5264,NaN,NaN,-0.0391,44
16,37,NaN,NaN,-0.0053,-2.0686,NaN,NaN,-0.2159,NaN,NaN,0.0463,46
17,48,NaN,NaN,-0.0286,-2.3010,NaN,NaN,2.6335,NaN,NaN,0.1332,47
18,35,NaN,NaN,-0.0037,-2.2175,NaN,NaN,-1.5577,NaN,NaN,0.1917,52
19,34,NaN,NaN,-0.0058,-2.2955,NaN,NaN,0.1239,NaN,NaN,0.0428,53
20,25,NaN,NaN,-0.0109,-1.9786,NaN,NaN,-0.2513,NaN,NaN,0.0161,54
21,44,NaN,NaN,-0.0104,-2.4990,NaN,NaN,0.7231,NaN,NaN,-0.0363,55
22,44,NaN,NaN,-0.0138,-2.0208,NaN,NaN,-0.0893,NaN,NaN,0.0733,57
23,34,NaN,NaN,-0.0108,-2.0208,NaN,NaN,-0.2822,NaN,NaN,0.0316,61
24,37,NaN,NaN,-0.0064,-2.6666,NaN,NaN,0.3401,NaN,NaN,0.2338,63
25,48,NaN,NaN,-0.0130,-2.7481,NaN,NaN,0.0007,NaN,NaN,0.0209,73
26,51,NaN,NaN,-0.0121,-2.5226,NaN,NaN,0.6732,NaN,NaN,0.0259,74
27,25,NaN,NaN,-0.0080,-2.0882,NaN,NaN,0.7699,NaN,NaN,-0.0052,78
28,37,NaN,NaN,-0.0071,-2.3184,NaN,NaN,-1.1219,NaN,NaN,1.7677,79
29,41,NaN,NaN,-0.0083,-2.4411,NaN,NaN,-0.8372,NaN,NaN,0.0972,83

In [9]:
cdf =df2.merge(df1, on='SN')

In [10]:
cdf

,SN,AGE_x,Hg (mg/L),Cd (mg/L),Pb (mg/L),Cr (mg/L),AGE_y,CYCLE,BLOOD GROUP,GENOTYPE,FSH 1 – 10 (miu/ml),LH 1 – 10.5 (miu/ml),PRL 1 – 16 (ng/ml)
0,2,36,6.6777,-0.0189,0.0755,0.4989,36,MENSES,O POS,AA,4.53,2.41,10.67
1,6,44,2.4756,-0.0065,0.0409,0.2351,44,MENSES,A POS,AS,3.72,5.13,27.45
2,7,35,0.7624,-0.0035,0.0604,-0.4379,35,MENSES,A POS,AA,4.16,6.38,42.52
3,10,39,0.4657,-0.0104,0.1126,-1.0635,39,MENSES,O POS,AA,2.39,3.79,4.76
4,11,44,-0.7568,-0.0147,0.0501,-0.7069,44,MENSES,A POS,AS,5.10,4.21,22.21
5,14,36,-0.6593,-0.0408,-0.0318,-0.7493,36,MENSES,O POS,AA,4.36,1.29,54.20
6,18,33,-0.9343,-0.0188,0.0035,-1.0267,33,MENSES,A POS,AS,4.56,8.27,30.41
7,23,35,-2.7321,-0.0130,0.0273,-1.1012,35,MENSES,B POS,AS,6.43,9.83,16.64
8,28,49,-2.6558,-0.0240,0.0210,-1.0158,49,NON MENSES,O POS,AS,5.17,6.96,6.49
9,31,24,-2.3514,-0.0104,0.0516,-1.9163,24,MENSES,B POS,AA,3.65,4.62,30.03
10,36,24,-2.8384,-0.0087,0.0525,-1.4783,24,MENSES,B POS,AA,9.63,23.50,15.43
11,38,40,-1.1419,-0.0125,0.0469,-1.5972,40,MENSES,O POS,AA,10.21,1.23,35.80
12,40,43,-1.6096,-0.0094,0.0748,-1.3596,43,MENSES,O POS,AA,17.12,8.39,10.75
13,41,42,-1.7066,-0.0076,-0.0590,-1.2802,42,NON MENSES,O POS,AA,6.32,5.01,40.42
14,43,28,-0.7858,-0.0122,-0.0461,-1.9279,28,MENSES,A POS,AA,5.20,2.83,10.20
15,44,30,-0.5264,-0.0120,-0.0391,-0.3216,30,MENSES,O POS,AA,5.02,9.40,12.46
16,46,37,-0.2159,-0.0053,0.0463,-2.0686,37,MENSES,B POS,AA,11.82,11.12,8.33
17,47,48,2.6335,-0.0286,0.1332,-2.3010,48,MENSES,B POS,AA,5.57,4.51,54.39
18,52,35,-1.5577,-0.0037,0.1917,-2.2175,35,MENSES,O POS,AA,4.62,3.12,9.67
19,53,34,0.1239,-0.0058,0.0428,-2.2955,34,MENSES,B POS,AA,4.35,7.10,15.75
20,54,25,-0.2513,-0.0109,0.0161,-1.9786,25,MENSES,A POS,AA,4.46,4.47,7.23
21,55,44,0.7231,-0.0104,-0.0363,-2.4990,44,MENSES,B POS,AS,3.62,5.20,28.12
22,57,44,-0.0893,-0.0138,0.0733,-2.0208,44,MENSES,A POS,AS,5.08,4.36,27.40
23,61,34,-0.2822,-0.0108,0.0316,-2.0208,34,MENSES,O POS,AS,4.25,7.27,28.17
24,63,37,0.3401,-0.0064,0.2338,-2.6666,37,MENSES,O POS,AS,5.42,7.84,14.53
25,73,48,0.0007,-0.0130,0.0209,-2.7481,48,NON MENSES,O POS,AA,77.22,61.15,10.50
26,74,51,0.6732,-0.0121,0.0259,-2.5226,51,NON MENSES,O POS,AA,96.55,70.42,13.47
27,78,25,0.7699,-0.0080,-0.0052,-2.0882,25,MENSES,O POS,AA,3.61,4.40,5.03
28,79,37,-1.1219,-0.0071,1.7677,-2.3184,37,MENSES,O POS,AA,5.61,5.28,17.16
29,83,41,-0.8372,-0.0083,0.0972,-2.4411,41,MENSES,O NEG,AA,9.22,6.25,12.38

In [11]:
Complete_dataset = cdf.copy()

In [12]:
Complete_dataset=Complete_dataset.drop(['AGE_y'], axis=1)

In [13]:
Complete_dataset

,SN,AGE_x,Hg (mg/L),Cd (mg/L),Pb (mg/L),Cr (mg/L),CYCLE,BLOOD GROUP,GENOTYPE,FSH 1 – 10 (miu/ml),LH 1 – 10.5 (miu/ml),PRL 1 – 16 (ng/ml)
0,2,36,6.6777,-0.0189,0.0755,0.4989,MENSES,O POS,AA,4.53,2.41,10.67
1,6,44,2.4756,-0.0065,0.0409,0.2351,MENSES,A POS,AS,3.72,5.13,27.45
2,7,35,0.7624,-0.0035,0.0604,-0.4379,MENSES,A POS,AA,4.16,6.38,42.52
3,10,39,0.4657,-0.0104,0.1126,-1.0635,MENSES,O POS,AA,2.39,3.79,4.76
4,11,44,-0.7568,-0.0147,0.0501,-0.7069,MENSES,A POS,AS,5.10,4.21,22.21
5,14,36,-0.6593,-0.0408,-0.0318,-0.7493,MENSES,O POS,AA,4.36,1.29,54.20
6,18,33,-0.9343,-0.0188,0.0035,-1.0267,MENSES,A POS,AS,4.56,8.27,30.41
7,23,35,-2.7321,-0.0130,0.0273,-1.1012,MENSES,B POS,AS,6.43,9.83,16.64
8,28,49,-2.6558,-0.0240,0.0210,-1.0158,NON MENSES,O POS,AS,5.17,6.96,6.49
9,31,24,-2.3514,-0.0104,0.0516,-1.9163,MENSES,B POS,AA,3.65,4.62,30.03
10,36,24,-2.8384,-0.0087,0.0525,-1.4783,MENSES,B POS,AA,9.63,23.50,15.43
11,38,40,-1.1419,-0.0125,0.0469,-1.5972,MENSES,O POS,AA,10.21,1.23,35.80
12,40,43,-1.6096,-0.0094,0.0748,-1.3596,MENSES,O POS,AA,17.12,8.39,10.75
13,41,42,-1.7066,-0.0076,-0.0590,-1.2802,NON MENSES,O POS,AA,6.32,5.01,40.42
14,43,28,-0.7858,-0.0122,-0.0461,-1.9279,MENSES,A POS,AA,5.20,2.83,10.20
15,44,30,-0.5264,-0.0120,-0.0391,-0.3216,MENSES,O POS,AA,5.02,9.40,12.46
16,46,37,-0.2159,-0.0053,0.0463,-2.0686,MENSES,B POS,AA,11.82,11.12,8.33
17,47,48,2.6335,-0.0286,0.1332,-2.3010,MENSES,B POS,AA,5.57,4.51,54.39
18,52,35,-1.5577,-0.0037,0.1917,-2.2175,MENSES,O POS,AA,4.62,3.12,9.67
19,53,34,0.1239,-0.0058,0.0428,-2.2955,MENSES,B POS,AA,4.35,7.10,15.75
20,54,25,-0.2513,-0.0109,0.0161,-1.9786,MENSES,A POS,AA,4.46,4.47,7.23
21,55,44,0.7231,-0.0104,-0.0363,-2.4990,MENSES,B POS,AS,3.62,5.20,28.12
22,57,44,-0.0893,-0.0138,0.0733,-2.0208,MENSES,A POS,AS,5.08,4.36,27.40
23,61,34,-0.2822,-0.0108,0.0316,-2.0208,MENSES,O POS,AS,4.25,7.27,28.17
24,63,37,0.3401,-0.0064,0.2338,-2.6666,MENSES,O POS,AS,5.42,7.84,14.53
25,73,48,0.0007,-0.0130,0.0209,-2.7481,NON MENSES,O POS,AA,77.22,61.15,10.50
26,74,51,0.6732,-0.0121,0.0259,-2.5226,NON MENSES,O POS,AA,96.55,70.42,13.47
27,78,25,0.7699,-0.0080,-0.0052,-2.0882,MENSES,O POS,AA,3.61,4.40,5.03
28,79,37,-1.1219,-0.0071,1.7677,-2.3184,MENSES,O POS,AA,5.61,5.28,17.16
29,83,41,-0.8372,-0.0083,0.0972,-2.4411,MENSES,O NEG,AA,9.22,6.25,12.38

In [14]:
Complete_dataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 30 entries, 0 to 29
Data columns (total 12 columns):
SN                       30 non-null int64
AGE_x                    30 non-null int64
Hg (mg/L)                30 non-null float64
Cd (mg/L)                30 non-null float64
Pb (mg/L)                30 non-null float64
Cr (mg/L)                30 non-null float64
CYCLE                    30 non-null object
BLOOD GROUP              30 non-null object
GENOTYPE                 30 non-null object
FSH 1 – 10 (miu/ml)      30 non-null float64
LH  1 – 10.5 (miu/ml)    30 non-null float64
PRL 1 – 16 (ng/ml)       30 non-null float64
dtypes: float64(7), int64(2), object(3)
memory usage: 3.0+ KB

In [16]:
export_excel = Complete_dataset.to_excel(r'C:\Users\Dickson\Documents\Dr. Gbenle\Complete_dataset.xlsx')

In [18]:
Complete_dataset['GENOTYPE'].unique()

array(['AA', 'AS'], dtype=object)

In [20]:
AS_Data = Complete_dataset[Complete_dataset.GENOTYPE == 'AS']
AA_Data = Complete_dataset[Complete_dataset.GENOTYPE == 'AA']

In [21]:
AS_Data

,SN,AGE_x,Hg (mg/L),Cd (mg/L),Pb (mg/L),Cr (mg/L),CYCLE,BLOOD GROUP,GENOTYPE,FSH 1 – 10 (miu/ml),LH 1 – 10.5 (miu/ml),PRL 1 – 16 (ng/ml)
1,6,44,2.4756,-0.0065,0.0409,0.2351,MENSES,A POS,AS,3.72,5.13,27.45
4,11,44,-0.7568,-0.0147,0.0501,-0.7069,MENSES,A POS,AS,5.10,4.21,22.21
6,18,33,-0.9343,-0.0188,0.0035,-1.0267,MENSES,A POS,AS,4.56,8.27,30.41
7,23,35,-2.7321,-0.0130,0.0273,-1.1012,MENSES,B POS,AS,6.43,9.83,16.64
8,28,49,-2.6558,-0.0240,0.0210,-1.0158,NON MENSES,O POS,AS,5.17,6.96,6.49
21,55,44,0.7231,-0.0104,-0.0363,-2.4990,MENSES,B POS,AS,3.62,5.20,28.12
22,57,44,-0.0893,-0.0138,0.0733,-2.0208,MENSES,A POS,AS,5.08,4.36,27.40
23,61,34,-0.2822,-0.0108,0.0316,-2.0208,MENSES,O POS,AS,4.25,7.27,28.17
24,63,37,0.3401,-0.0064,0.2338,-2.6666,MENSES,O POS,AS,5.42,7.84,14.53

In [22]:
AA_Data

,SN,AGE_x,Hg (mg/L),Cd (mg/L),Pb (mg/L),Cr (mg/L),CYCLE,BLOOD GROUP,GENOTYPE,FSH 1 – 10 (miu/ml),LH 1 – 10.5 (miu/ml),PRL 1 – 16 (ng/ml)
0,2,36,6.6777,-0.0189,0.0755,0.4989,MENSES,O POS,AA,4.53,2.41,10.67
2,7,35,0.7624,-0.0035,0.0604,-0.4379,MENSES,A POS,AA,4.16,6.38,42.52
3,10,39,0.4657,-0.0104,0.1126,-1.0635,MENSES,O POS,AA,2.39,3.79,4.76
5,14,36,-0.6593,-0.0408,-0.0318,-0.7493,MENSES,O POS,AA,4.36,1.29,54.20
9,31,24,-2.3514,-0.0104,0.0516,-1.9163,MENSES,B POS,AA,3.65,4.62,30.03
10,36,24,-2.8384,-0.0087,0.0525,-1.4783,MENSES,B POS,AA,9.63,23.50,15.43
11,38,40,-1.1419,-0.0125,0.0469,-1.5972,MENSES,O POS,AA,10.21,1.23,35.80
12,40,43,-1.6096,-0.0094,0.0748,-1.3596,MENSES,O POS,AA,17.12,8.39,10.75
13,41,42,-1.7066,-0.0076,-0.0590,-1.2802,NON MENSES,O POS,AA,6.32,5.01,40.42
14,43,28,-0.7858,-0.0122,-0.0461,-1.9279,MENSES,A POS,AA,5.20,2.83,10.20
15,44,30,-0.5264,-0.0120,-0.0391,-0.3216,MENSES,O POS,AA,5.02,9.40,12.46
16,46,37,-0.2159,-0.0053,0.0463,-2.0686,MENSES,B POS,AA,11.82,11.12,8.33
17,47,48,2.6335,-0.0286,0.1332,-2.3010,MENSES,B POS,AA,5.57,4.51,54.39
18,52,35,-1.5577,-0.0037,0.1917,-2.2175,MENSES,O POS,AA,4.62,3.12,9.67
19,53,34,0.1239,-0.0058,0.0428,-2.2955,MENSES,B POS,AA,4.35,7.10,15.75
20,54,25,-0.2513,-0.0109,0.0161,-1.9786,MENSES,A POS,AA,4.46,4.47,7.23
25,73,48,0.0007,-0.0130,0.0209,-2.7481,NON MENSES,O POS,AA,77.22,61.15,10.50
26,74,51,0.6732,-0.0121,0.0259,-2.5226,NON MENSES,O POS,AA,96.55,70.42,13.47
27,78,25,0.7699,-0.0080,-0.0052,-2.0882,MENSES,O POS,AA,3.61,4.40,5.03
28,79,37,-1.1219,-0.0071,1.7677,-2.3184,MENSES,O POS,AA,5.61,5.28,17.16
29,83,41,-0.8372,-0.0083,0.0972,-2.4411,MENSES,O NEG,AA,9.22,6.25,12.38

In [23]:
Complete_dataset['BLOOD GROUP'].unique()

array(['O POS', 'A POS', 'B POS', 'O NEG'], dtype=object)

In [27]:
O_Positive_data = Complete_dataset[Complete_dataset['BLOOD GROUP'] == 'O POS']
A_Positive_data = Complete_dataset[Complete_dataset['BLOOD GROUP'] == 'A POS']
B_Positive_data = Complete_dataset[Complete_dataset['BLOOD GROUP'] == 'B POS']
O_Negative_data = Complete_dataset[Complete_dataset['BLOOD GROUP'] == 'O NEG']

In [28]:
O_Negative_data

,SN,AGE_x,Hg (mg/L),Cd (mg/L),Pb (mg/L),Cr (mg/L),CYCLE,BLOOD GROUP,GENOTYPE,FSH 1 – 10 (miu/ml),LH 1 – 10.5 (miu/ml),PRL 1 – 16 (ng/ml)
29,83,41,-0.8372,-0.0083,0.0972,-2.4411,MENSES,O NEG,AA,9.22,6.25,12.38

In [30]:
O_Positive_data

,SN,AGE_x,Hg (mg/L),Cd (mg/L),Pb (mg/L),Cr (mg/L),CYCLE,BLOOD GROUP,GENOTYPE,FSH 1 – 10 (miu/ml),LH 1 – 10.5 (miu/ml),PRL 1 – 16 (ng/ml)
0,2,36,6.6777,-0.0189,0.0755,0.4989,MENSES,O POS,AA,4.53,2.41,10.67
3,10,39,0.4657,-0.0104,0.1126,-1.0635,MENSES,O POS,AA,2.39,3.79,4.76
5,14,36,-0.6593,-0.0408,-0.0318,-0.7493,MENSES,O POS,AA,4.36,1.29,54.20
8,28,49,-2.6558,-0.0240,0.0210,-1.0158,NON MENSES,O POS,AS,5.17,6.96,6.49
11,38,40,-1.1419,-0.0125,0.0469,-1.5972,MENSES,O POS,AA,10.21,1.23,35.80
12,40,43,-1.6096,-0.0094,0.0748,-1.3596,MENSES,O POS,AA,17.12,8.39,10.75
13,41,42,-1.7066,-0.0076,-0.0590,-1.2802,NON MENSES,O POS,AA,6.32,5.01,40.42
15,44,30,-0.5264,-0.0120,-0.0391,-0.3216,MENSES,O POS,AA,5.02,9.40,12.46
18,52,35,-1.5577,-0.0037,0.1917,-2.2175,MENSES,O POS,AA,4.62,3.12,9.67
23,61,34,-0.2822,-0.0108,0.0316,-2.0208,MENSES,O POS,AS,4.25,7.27,28.17
24,63,37,0.3401,-0.0064,0.2338,-2.6666,MENSES,O POS,AS,5.42,7.84,14.53
25,73,48,0.0007,-0.0130,0.0209,-2.7481,NON MENSES,O POS,AA,77.22,61.15,10.50
26,74,51,0.6732,-0.0121,0.0259,-2.5226,NON MENSES,O POS,AA,96.55,70.42,13.47
27,78,25,0.7699,-0.0080,-0.0052,-2.0882,MENSES,O POS,AA,3.61,4.40,5.03
28,79,37,-1.1219,-0.0071,1.7677,-2.3184,MENSES,O POS,AA,5.61,5.28,17.16